import localFont from "next/font/local";
import "./globals.css";
import { Ubuntu_Mono } from "next/font/google";

const montrealBold = localFont({
  src: "./fonts/Montreal-Bold.ttf",
  variable: "--font-montreal-bold",
  weight: "700",
});
const montrealRegular = localFont({
  src: "./fonts/Montreal-Regular.ttf",
  variable: "--font-montreal-regular",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montrealRegular.className} ${montrealBold.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
